[bans]
multiple-versions = "allow"

[licenses]
allow = [
      "Apache-2.0",
      "BSD-2-Clause",
      "BSD-3-Clause",
      "ISC",
      "MIT",
      "OpenSSL",
      "Unicode-DFS-2016",
      "Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
      { path = "LICENSE", hash = 0xbd0eed23 },
]

[advisories]
ignore = [
      # While the general concern is valid, the use of the APIs here
      # is not affected.  Later versions of iroh did migrate to the
      # safer APIs, but this is a rather invasive change which will
      # not happen on the maintenance branch.
      "RUSTSEC-2022-0093",
]